### PR TITLE
Updated to 1.21

### PR DESCRIPTION
**Pull request by MBrinks2239**
Updated the mod for 1.21, please make a branch for 1.21 to merge to. Also, I humbly request that you also put this mod on modrinth.

### CODE REVIEW

**Comment by Ocraftj** [comment]
you are amazing for updating this mod. I do want to ask though, if you can, could you add the updated mod as a release to your fork or publish it onto modrinth or curseforge? I really want to use it and I don't expect the original creator to come back after a year.

**Comment by MBrinks2239** [comment]
@Ocraftj 
[elytra-chestplate-swapper-1.3.0-MC1.21.zip](https://github.com/user-attachments/files/16094224/elytra-chestplate-swapper-1.3.0-MC1.21.zip)

Here you go, this is the compiled version.

Also @Saphjyr could you please check out this PR?

**Comment by Ocraftj** [comment]
thank you!!! that was fast!!!

**Comment by Saphjyr** [comment]
Thank you so much for this PR. I'll push the mod after doing some tests on it.

By the way, if you (or anyone) want to be maintainer on this project, I can grant you access.

I am willing to update this mod from time to time, but I'm usually not available for new minecraft versions. So if someone wants to do it i'll gladly give them access.

**Pull request merged**
